// Text constants
export const TEXTS = {
  SITE: {
    TITLE: 'Development Blog',
    DESCRIPTION: 'A space to share stories about development and technology.',
    AUTHOR: 'Developer',
  },
  NAV: {
    HOME: 'Home',
    POSTS: 'Posts',
    LOGIN: 'Login',
    LOGOUT: 'Logout',
    ADMIN: 'Admin',
    DASHBOARD: 'Dashboard',
    MANAGE_POSTS: 'Manage Posts',
    NEW_POST: 'New Post',
  },
  POSTS: {
    READ_MORE: 'Read More',
    PUBLISHED_AT: 'Published',
    VIEWS: 'Views',
    NO_POSTS: 'No posts available.',
    LOADING: 'Loading...',
    STATUS: 'Status',
    DRAFT: 'Draft',
    PUBLISHED: 'Published',
    TITLE: 'Title',
    CONTENT: 'Content',
    EXCERPT: 'Excerpt',
    SLUG: 'URL Slug',
    COVER_IMAGE: 'Cover Image',
    TAGS: 'Tags',
    ACTIONS: 'Actions',
    EDIT: 'Edit',
    DELETE: 'Delete',
    SAVE: 'Save',
    PUBLISH: 'Publish',
    UNPUBLISH: 'Unpublish',
    SAVE_SUCCESS: 'Post saved successfully',
    PUBLISH_SUCCESS: 'Post published successfully',
    DELETE_SUCCESS: 'Post deleted successfully',
    DELETE_CONFIRM: 'Are you sure you want to delete this post?',
    PREVIEW: 'Preview',
    SAVE_DRAFT: 'Save as Draft',
  },
  COMMENTS: {
    TITLE: 'Comments',
    WRITE: 'Write a comment',
    SUBMIT: 'Submit',
    LOGIN_REQUIRED: 'Please login to comment',
    NO_COMMENTS: 'No comments yet. Be the first to comment!',
    DELETE_CONFIRM: 'Are you sure you want to delete this comment?',
    DELETE_SUCCESS: 'Comment deleted successfully',
  },
  AUTH: {
    LOGIN_WITH_GOOGLE: 'Login with Google',
    LOGIN_SUCCESS: 'Successfully logged in',
    LOGOUT_SUCCESS: 'Successfully logged out',
    LOGIN_ERROR: 'Login failed',
    LOGOUT_ERROR: 'Logout failed',
    ADMIN_ONLY: 'Admin access only',
  },
  ADMIN: {
    TITLE: 'Admin Dashboard',
    STATS: {
      TOTAL_POSTS: 'Total Posts',
      TOTAL_VIEWS: 'Total Views',
      TOTAL_COMMENTS: 'Total Comments',
    },
    RECENT: {
      POSTS: 'Recent Posts',
      COMMENTS: 'Recent Comments',
    },
    DASHBOARD_TITLE: 'Admin Dashboard',
    TOTAL_POSTS: 'Total Posts',
    TOTAL_COMMENTS: 'Total Comments',
    TOTAL_VIEWS: 'Total Views',
    RECENT_POSTS: 'Recent Posts',
    RECENT_COMMENTS: 'Recent Comments',
    PUBLISH_SUCCESS: 'Post published successfully',
    SAVE_SUCCESS: 'Post saved successfully',
    DELETE_SUCCESS: 'Post deleted successfully',
    CONFIRM_DELETE: 'Are you sure you want to delete this post?'
  },
  ERRORS: {
    GENERAL: 'An error occurred. Please try again.',
    NOT_FOUND: 'Page not found',
    UNAUTHORIZED: 'Unauthorized access',
    FORBIDDEN: 'Access forbidden',
    AUTH_REQUIRED: 'Authentication required',
    ADMIN_PERMISSION: 'Admin permission required',
    DUPLICATE_SLUG: 'Duplicate slug detected',
    DATABASE_ACCESS: 'Database access error',
  },
  FORMS: {
    PLACEHOLDERS: {
      COMMENT: 'Write your comment here...',
      TITLE: 'Enter the title...',
      SLUG: 'Enter the URL slug...',
      EXCERPT: 'Enter the excerpt...',
      COVER_IMAGE: 'Enter the cover image URL...',
      CONTENT: 'Enter the content...'
    },
    CANCEL: 'Cancel',
    LOADING: 'Loading...',
    SAVE: 'Save',
  },
  NAVIGATION: {
    HOME: 'Home',
    ADMIN: 'Admin',
    DASHBOARD: 'Dashboard',
    MANAGE_POSTS: 'Manage Posts',
    NEW_POST: 'New Post',
    LOGIN: 'Login',
    LOGOUT: 'Logout'
  },
} as const

// Style constants
export const STYLES = {
  COLORS: {
    PRIMARY: 'text-blue-600',
    SECONDARY: 'text-gray-600',
    SUCCESS: 'text-green-600',
    DANGER: 'text-red-600',
    WARNING: 'text-yellow-600',
    INFO: 'text-blue-400',
  },
  BACKGROUNDS: {
    PRIMARY: 'bg-blue-600',
    SECONDARY: 'bg-gray-600',
    SUCCESS: 'bg-green-600',
    DANGER: 'bg-red-600',
    WARNING: 'bg-yellow-600',
    INFO: 'bg-blue-400',
  },
  STATUS: {
    DRAFT: 'bg-gray-100 text-gray-800',
    PUBLISHED: 'bg-green-100 text-green-800',
  },
  SPACING: {
    XS: '0.25rem',
    SM: '0.5rem',
    MD: '1rem',
    LG: '1.5rem',
    XL: '2rem',
    XXL: '3rem',
    POST: {
      HEADER_PADDING: '2.5rem',
      CONTENT_PADDING: '2rem',
    }
  },
  BORDER_RADIUS: {
    SM: '0.25rem',
    MD: '0.5rem',
    LG: '0.75rem',
    XL: '1rem',
    POST: {
      COVER: '0.75rem',
      AVATAR: '50%',
    }
  },
  FONT_SIZE: {
    XS: '0.75rem',
    SM: '0.875rem',
    BASE: '1rem',
    LG: '1.125rem',
    XL: '1.25rem',
    XXL: '1.5rem',
    XXXL: '2rem',
    POST: {
      TITLE: '2.5rem',
      AUTHOR: '1rem',
      DATE: '0.875rem',
      CONTENT: '1.125rem',
    }
  },
  FONT_WEIGHT: {
    NORMAL: '400',
    MEDIUM: '500',
    SEMIBOLD: '600',
    BOLD: '700',
  },
  BREAKPOINTS: {
    SM: '640px',
    MD: '768px',
    LG: '1024px',
    XL: '1280px',
  },
} as const 